config/routes.rb
Rails.application.routes.draw do
  resources :books
  get "/", to: "books#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "好書建立成功!!"
      redirect_to books_path
    else
      render "new"
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    if @book.update(book_params)
        redirect_to books_path, notice: "更新成功!!"
    else
        render "edit"
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    flash[:notice] = "刪除成功!!"
    redirect_to books_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :year, :image, :image_cache, :remove_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= simple_form_for(book) do |f| %>

  <div class="field">
    <%= f.input :name, label: "書名" %>
  </div>

  <div class="field">
    <%= f.input :author, label: "作者" %>
  </div>

  <div class="field">
    <%= f.input :year, label: "出版年" %>
  </div>
  
  <div class="field">
    <%= f.input :image %> <!-- 上傳 -->
    <%= f.check_box :remove_image, label: "刪除圖片" %> <!-- 刪除 -->
    <%= f.hidden_field :image_cache %> <!-- 快取 _cache (讓填表時若有誤，不用重新選擇圖片) -->
    <%= image_tag @book.image if @book.image? %> <!-- 如果 book 已有圖片的話，就顯示 -->
  </div>

  <div class="actions">
    <%= f.button :submit, "更新好書", class: "btn btn-success"%>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>編輯好書</h1>

<%= render 'form', book: @book %>

<%= link_to '詳細介紹', @book, class: "btn btn-info btn-xs" %> |
<%= link_to '回上一頁', books_path, class: "btn btn-default btn-xs" %>

app/views/books/index.html.erb
<body id="page-top">
  <header class="masthead text-center text-white d-flex">
    <div class="title">
      <div class="row">
        <div class="col-lg-10 mx-auto">
          <h1 class="text-uppercase">
            <strong>好書推薦</strong>
          </h1>
           <hr>
          <%= link_to '馬上新增好書', new_book_path, class: "btn btn-default" %>
         
        </div>
        
        <div class="col-lg-8 mx-auto">
         
          
        </div>
      </div>
    </div>
  </header>

    
   
  
  <table class = "table">
    <thead>
      <tr>
        <td>書名</td>
        <td>作者</td>
        <td>出版年</td>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.name %></td>
          <td><%= book.author %></td>
          <td><%= book.year %></td>
          <td><%= link_to "詳細簡介", book_path(book), class: "btn btn-info btn-xs" %></td>
          <td><%= link_to "編輯好書", edit_book_path(book), class: "btn btn-warning btn-xs" %></td>
          <td><%= link_to "刪除好書", book_path(book), method: "delete", data: {confirm: "are you sure ?!", class: "btn btn-danger btn-xs"} %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
    </tfoot>
  </table>
</body>

app/views/books/new.html.erb
<div class="new">
  <h1><strong>新增好書</strong></h1>
  <%= render 'form', book: @book %>

  <%= link_to '回上一頁', books_path, class: "btn btn-default btn-xs" %>

</div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>書名:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>作者:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>出版年:</strong>
  <%= @book.year %>
</p>

<p>
  <strong>書本封面：</strong></br>
  <%= image_tag @book.image if @book.image? %> <!-- 如果 book 已有圖片的話，就顯示 -->
</p>

<%= link_to '編輯好書', edit_book_path(@book), class: "btn btn-warning btn-xs" %> |
<%= link_to '回上一頁', books_path, class: "btn btn-default btn-xs" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>好書推薦</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    
    <%= image_tag "book_bg.jpg", class: 'style_bg' %>
    <div class="block"></div>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-warning" role="alert"><%= flash[:notice] %></div>
      <% end %>
      <%= yield %>  
    </div>
    
    
    <!-- app/views/layouts/application.html.erb -->
    <div id="modal-holder"></div>
  </body>
</html>